server:
  port: 5000

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: my-first-stream
          group: myStream-group
          content-type: application/json
          consumer:
            checkpointMode: batch
        output:
          destination: my-first-stream
          content-type: application/json


cloud:
  aws:
    credentials:
      use-default-aws-credentials-chain: false
    region:
      static: eu-west-1
      auto: false
    stack:
      auto: false
